### ISSUE TITLE
If specified batch_size > number of samples - errors out

### ISSUE THREAD

**Issue by robertamezquita** [drisso/mbkmeans#12]
Might be worth keeping this error, but then if thats the case not sure whats happening when batch size is not cleanly divisible by total number of samples. This only happens if there is 1 batch (e.g. SCE is 500 cells, you specify a batch size of 501, it errors out; if its 333, no error).

A small tweak that if specified batch size is too large to just use all the data and then supply a warning message might be an ideal solution

**Comment by drisso** [comment]
Hi @robertamezquita ,

If you have 500 cells and choose a batch size of 333, at each iteration you randomly sample 333 cells. That's fine.

Obviously, you cannot sample 501 cells, hence the error. I'm not sure that it's worth turning this into a warning as this is obviously something the user did not intend to do (to use a batch greater than the number of cells).

Imagine someone has 500 cells and meant to write `batch_size=100` and wrote `batch_size=1000`, I think it's safer to error out and force the user to check the code.

But I'm happy to change my mind if you have a compelling case against the error and in favor of the warning.

**Comment by robertamezquita** [comment]
Yeah I think its fair to leave it as an error - I'm thinking of cases where running `mbkmeans` might be automated and where the user would have to adjust the batch size, but if you're running `mbkmeans`, you probably won't realistically run into this often. Just wanted to point this out in case it was undesirable!
